using System.Collections.Generic;
using WeatherObjects;

namespace WeatherApplication.Services
{
    public static class CountryCollection
    {
        public static List<Country> Countries = new List<Country>()
        {
//new Country(){Name = "Afghanistan", CountryCode = "AF" },
//new Country(){Name = "Ã…land Islands", CountryCode = "AX" },
new Country(){Name = "Albania", CountryCode = "AL" },
//new Country(){Name = "Algeria", CountryCode = "DZ" },
//new Country(){Name = "American Samoa", CountryCode = "AS" },
//new Country(){Name = "Andorra", CountryCode = "AD" },
//new Country(){Name = "Angola", CountryCode = "AO" },
//new Country(){Name = "Anguilla", CountryCode = "AI" },
//new Country(){Name = "Antarctica", CountryCode = "AQ" },
//new Country(){Name = "Antigua and Barbuda", CountryCode = "AG" },
new Country(){Name = "Argentina", CountryCode = "AR" },
//new Country(){Name = "Armenia", CountryCode = "AM" },
//new Country(){Name = "Aruba", CountryCode = "AW" },
new Country(){Name = "Australia", CountryCode = "AU" },
new Country(){Name = "Austria", CountryCode = "AT" },
//new Country(){Name = "Azerbaijan", CountryCode = "AZ" },
//new Country(){Name = "Bahamas", CountryCode = "BS" },
//new Country(){Name = "Bahrain", CountryCode = "BH" },
//new Country(){Name = "Bangladesh", CountryCode = "BD" },
//new Country(){Name = "Barbados", CountryCode = "BB" },
new Country(){Name = "Belarus", CountryCode = "BY" },
new Country(){Name = "Belgium", CountryCode = "BE" },
//new Country(){Name = "Belize", CountryCode = "BZ" },
//new Country(){Name = "Benin", CountryCode = "BJ" },
//new Country(){Name = "Bermuda", CountryCode = "BM" },
//new Country(){Name = "Bhutan", CountryCode = "BT" },
//new Country(){Name = "Bolivia", CountryCode= "BO" },
//new Country(){Name = "Bosnia and Herzegovina", CountryCode = "BA" },
//new Country(){Name = "Botswana", CountryCode = "BW" },
//new Country(){Name = "Bouvet Island", CountryCode = "BV" },
new Country(){Name = "Brazil", CountryCode = "BR" },
//new Country(){Name = "British Indian Ocean Territory", CountryCode = "IO" },
//new Country(){Name = "Brunei Darussalam", CountryCode = "BN" },
//new Country(){Name = "Bulgaria", CountryCode = "BG" },
//new Country(){Name = "Burkina Faso", CountryCode = "BF" },
//new Country(){Name = "Burundi", CountryCode = "BI" },
//new Country(){Name = "Cambodia", CountryCode = "KH" },
//new Country(){Name = "Cameroon", CountryCode = "CM" },
//new Country(){Name = "Canada", CountryCode = "CA" },
//new Country(){Name = "Cape Verde", CountryCode = "CV" },
//new Country(){Name = "Cayman Islands", CountryCode = "KY" },
//new Country(){Name = "Central African Republic", CountryCode = "CF" },
//new Country(){Name = "Chad", CountryCode = "TD" },
//new Country(){Name = "Chile", CountryCode = "CL" },
new Country(){Name = "China", CountryCode = "CN" },
//new Country(){Name = "Christmas Island", CountryCode = "CX" },
//new Country(){Name = "Cocos(Keeling) Islands", CountryCode = "CC" },
//new Country(){Name = "Colombia", CountryCode = "CO" },
//new Country(){Name = "Comoros", CountryCode = "KM" },
//new Country(){Name = "Congo", CountryCode = "CG" },
//new Country(){Name = "Congo", CountryCode = "CD" },
//new Country(){Name = "Cook Islands", CountryCode = "CK" },
//new Country(){Name = "Costa Rica", CountryCode = "CR" },
//new Country(){Name = "CÃ´te d'Ivoire", CountryCode = "CI" },
new Country(){Name = "Croatia", CountryCode = "HR" },
new Country(){Name = "Cuba", CountryCode = "CU" },
//new Country(){Name = "CuraÃ§ao", CountryCode = "CW" },
//new Country(){Name = "Cyprus", CountryCode = "CY" },
new Country(){Name = "Czech Republic", CountryCode = "CZ" },
new Country(){Name = "Denmark", CountryCode = "DK" },
//new Country(){Name = "Djibouti", CountryCode = "DJ" },
//new Country(){Name = "Dominica", CountryCode = "DM" },
new Country(){Name = "Dominican Republic", CountryCode = "DO" },
new Country(){Name = "Ecuador", CountryCode = "EC" },
new Country(){Name = "Egypt", CountryCode = "EG" },
//new Country(){Name = "El Salvador", CountryCode = "SV" },
//new Country(){Name = "Equatorial Guinea", CountryCode = "GQ" },
//new Country(){Name = "Eritrea", CountryCode = "ER" },
//new Country(){Name = "Estonia", CountryCode = "EE" },
//new Country(){Name = "Ethiopia", CountryCode = "ET" },
//new Country(){Name = "Falkland Islands(Malvinas)", CountryCode = "FK" },
//new Country(){Name = "Faroe Islands", CountryCode = "FO" },
//new Country(){Name = "Fiji", CountryCode = "FJ" },
new Country(){Name = "Finland", CountryCode = "FI" },
new Country(){Name = "France", CountryCode = "FR" },
//new Country(){Name = "French Guiana", CountryCode = "GF" },
//new Country(){Name = "French Polynesia", CountryCode = "PF" },
//new Country(){Name = "French Southern Territories", CountryCode = "TF" },
//new Country(){Name = "Gabon", CountryCode = "GA" },
//new Country(){Name = "Gambia", CountryCode = "GM" },
//new Country(){Name = "Georgia", CountryCode = "GE" },
new Country(){Name = "Germany", CountryCode = "DE" },
new Country(){Name = "Ghana", CountryCode = "GH" },
//new Country(){Name = "Gibraltar", CountryCode = "GI" },
new Country(){Name = "Greece", CountryCode = "GR" },
//new Country(){Name = "Greenland", CountryCode = "GL" },
//new Country(){Name = "Grenada", CountryCode = "GD" },
//new Country(){Name = "Guadeloupe", CountryCode = "GP" },
//new Country(){Name = "Guam", CountryCode = "GU" },
//new Country(){Name = "Guatemala", CountryCode = "GT" },
//new Country(){Name = "Guernsey", CountryCode = "GG" },
//new Country(){Name = "Guinea", CountryCode = "GN" },
//new Country(){Name = "Guinea-Bissau", CountryCode = "GW" },
//new Country(){Name = "Guyana", CountryCode = "GY" },
//new Country(){Name = "Haiti", CountryCode = "HT" },
//new Country(){Name = "Heard Island and McDonald Islands", CountryCode = "HM" },
//new Country(){Name = "Holy See(Vatican City State)", CountryCode = "VA" },
//new Country(){Name = "Honduras", CountryCode = "HN" },
//new Country(){Name = "Hong Kong", CountryCode = "HK" },
new Country(){Name = "Hungary", CountryCode = "HU" },
new Country(){Name = "Iceland", CountryCode = "IS" },
new Country(){Name = "India", CountryCode = "IN" },
//new Country(){Name = "Indonesia", CountryCode = "ID" },
new Country(){Name = "Iran", CountryCode = "IR" },
//new Country(){Name = "Iraq", CountryCode = "IQ" },
new Country(){Name = "Ireland", CountryCode = "IE" },
//new Country(){Name = "Isle of Man", CountryCode = "IM" },
//new Country(){Name = "Israel", CountryCode = "IL" },
new Country(){Name = "Italy", CountryCode = "IT" },
new Country(){Name = "Jamaica", CountryCode = "JM" },
new Country(){Name = "Japan", CountryCode = "JP" },
//new Country(){Name = "Jersey", CountryCode = "JE" },
//new Country(){Name = "Jordan", CountryCode = "JO" },
//new Country(){Name = "Kazakhstan", CountryCode = "KZ" },
//new Country(){Name = "Kenya", CountryCode = "KE" },
//new Country(){Name = "Kiribati", CountryCode = "KI" },
//new Country(){Name = "Korea", CountryCode = "KP" },
//new Country(){Name = "Kuwait", CountryCode = "KW" },
//new Country(){Name = "Kyrgyzstan", CountryCode = "KG" },
//new Country(){Name = "Lao People's Democratic Republic", CountryCode = "LA" },
//new Country(){Name = "Latvia", CountryCode = "LV" },
//new Country(){Name = "Lebanon", CountryCode = "LB" },
//new Country(){Name = "Lesotho", CountryCode = "LS" },
//new Country(){Name = "Liberia", CountryCode = "LR" },
//new Country(){Name = "Libya", CountryCode = "LY" },
//new Country(){Name = "Liechtenstein", CountryCode = "LI" },
//new Country(){Name = "Lithuania", CountryCode = "LT" },
//new Country(){Name = "Luxembourg", CountryCode = "LU" },
//new Country(){Name = "Macao", CountryCode = "MO" },
//new Country(){Name = "Macedonia", CountryCode =  "MK" },
new Country(){Name = "Madagascar", CountryCode = "MG" },
//new Country(){Name = "Malawi", CountryCode = "MW" },
new Country(){Name = "Malaysia", CountryCode = "MY" },
//new Country(){Name = "Maldives", CountryCode = "MV" },
//new Country(){Name = "Mali", CountryCode = "ML" },
//new Country(){Name = "Malta", CountryCode = "MT" },
//new Country(){Name = "Marshall Islands", CountryCode = "MH" },
//new Country(){Name = "Martinique", CountryCode = "MQ" },
//new Country(){Name = "Mauritania", CountryCode = "MR" },
//new Country(){Name = "Mauritius", CountryCode = "MU" },
//new Country(){Name = "Mayotte", CountryCode = "YT" },
new Country(){Name = "Mexico", CountryCode = "MX" },
//new Country(){Name = "Monaco", CountryCode = "MC" },
//new Country(){Name = "Mongolia", CountryCode = "MN" },
new Country(){Name = "Montenegro", CountryCode = "ME" },
//new Country(){Name = "Montserrat", CountryCode = "MS" },
//new Country(){Name = "Morocco", CountryCode = "MA" },
//new Country(){Name = "Mozambique", CountryCode = "MZ" },
//new Country(){Name = "Myanmar", CountryCode = "MM" },
//new Country(){Name = "Namibia", CountryCode = "NA" },
//new Country(){Name = "Nauru", CountryCode = "NR" },
//new Country(){Name = "Nepal", CountryCode = "NP" },
new Country(){Name = "Netherlands", CountryCode = "NL" },
//new Country(){Name = "New Caledonia", CountryCode = "NC" },
new Country(){Name = "New Zealand", CountryCode = "NZ" },
//new Country(){Name = "Nicaragua", CountryCode = "NI" },
new Country(){Name = "Niger", CountryCode = "NE" },
//new Country(){Name = "Nigeria", CountryCode = "NG" },
//new Country(){Name = "Niue", CountryCode = "NU" },
//new Country(){Name = "Norfolk Island", CountryCode = "NF" },
//new Country(){Name = "Northern Mariana Islands", CountryCode = "MP" },
new Country(){Name = "Norway", CountryCode = "NO" },
//new Country(){Name = "Oman", CountryCode = "OM" },
new Country(){Name = "Pakistan", CountryCode = "PK" },
//new Country(){Name = "Palau", CountryCode = "PW" },
//new Country(){Name = "Panama", CountryCode = "PA" },
//new Country(){Name = "Papua New Guinea", CountryCode = "PG" },
new Country(){Name = "Paraguay", CountryCode = "PY" },
//new Country(){Name = "Peru", CountryCode = "PE" },
//new Country(){Name = "Philippines", CountryCode = "PH" },
//new Country(){Name = "Pitcairn", CountryCode = "PN" },
new Country(){Name = "Poland", CountryCode = "PL" },
new Country(){Name = "Portugal", CountryCode = "PT" },
//new Country(){Name = "Puerto Rico", CountryCode = "PR" },
//new Country(){Name = "Qatar", CountryCode = "QA" },
//new Country(){Name = "RÃ©union", CountryCode = "RE" },
new Country(){Name = "Romania", CountryCode = "RO" },
new Country(){Name = "Russian Federation", CountryCode = "RU" },
//new Country(){Name = "Rwanda", CountryCode = "RW" },
//new Country(){Name = "Saint BarthÃ©lemy", CountryCode = "BL" },
//new Country(){Name = "Saint Kitts and Nevis", CountryCode = "KN" },
//new Country(){Name = "Saint Lucia", CountryCode = "LC" },
//new Country(){Name = "Saint Martin(French part)", CountryCode = "MF" },
//new Country(){Name = "Saint Pierre and Miquelon", CountryCode = "PM" },
//new Country(){Name = "Saint Vincent and the Grenadines", CountryCode = "VC" },
//new Country(){Name = "Samoa", CountryCode = "WS" },
//new Country(){Name = "San Marino", CountryCode = "SM" },
//new Country(){Name = "Sao Tome and Principe", CountryCode = "ST" },
new Country(){Name = "Saudi Arabia", CountryCode = "SA" },
//new Country(){Name = "Senegal", CountryCode = "SN" },
//new Country(){Name = "Serbia", CountryCode = "RS" },
//new Country(){Name = "Seychelles", CountryCode = "SC" },
//new Country(){Name = "Sierra Leone", CountryCode = "SL" },
//new Country(){Name = "Singapore", CountryCode = "SG" },
//new Country(){Name = "Sint Maarten(Dutch part)", CountryCode = "SX" },
//new Country(){Name = "Slovakia", CountryCode = "SK" },
new Country(){Name = "Slovenia", CountryCode = "SI" },
//new Country(){Name = "Solomon Islands", CountryCode = "SB" },
//new Country(){Name = "Somalia", CountryCode = "SO" },
new Country(){Name = "South Africa", CountryCode = "ZA" },
//new Country(){Name = "South Sudan", CountryCode = "SS" },
new Country(){Name = "Spain", CountryCode = "ES" },
//new Country(){Name = "Sri Lanka", CountryCode = "LK" },
//new Country(){Name = "Sudan", CountryCode = "SD" },
//new Country(){Name = "Suriname", CountryCode = "SR" },
//new Country(){Name = "Svalbard and Jan Mayen", CountryCode = "SJ" },
//new Country(){Name = "Swaziland", CountryCode = "SZ" },
new Country(){Name = "Sweden", CountryCode = "SE" },
new Country(){Name = "Switzerland", CountryCode = "CH" },
//new Country(){Name = "Syrian Arab Republic", CountryCode = "SY" },
//new Country(){Name = "Tajikistan", CountryCode = "TJ" },
new Country(){Name = "Thailand", CountryCode = "TH" },
//new Country(){Name = "Timor-Leste", CountryCode = "TL" },
//new Country(){Name = "Togo", CountryCode = "TG" },
//new Country(){Name = "Tokelau", CountryCode = "TK" },
//new Country(){Name = "Tonga", CountryCode = "TO" },
//new Country(){Name = "Trinidad and Tobago", CountryCode = "TT" },
//new Country(){Name = "Tunisia", CountryCode = "TN" },
new Country(){Name = "Turkey", CountryCode = "TR" },
//new Country(){Name = "Turkmenistan", CountryCode = "TM" },
//new Country(){Name = "Turks and Caicos Islands", CountryCode = "TC" },
//new Country(){Name = "Tuvalu", CountryCode = "TV" },
new Country(){Name = "Uganda", CountryCode = "UG" },
new Country(){Name = "Ukraine", CountryCode = "UA" },
//new Country(){Name = "United Arab Emirates", CountryCode = "AE" },
new Country(){Name = "United Kingdom", CountryCode = "GB" },
new Country(){Name = "United States", CountryCode = "US" },
//new Country(){Name = "United States Minor Outlying Islands", CountryCode = "UM" },
new Country(){Name = "Uruguay", CountryCode = "UY" },
//new Country(){Name = "Uzbekistan", CountryCode = "UZ" },
//new Country(){Name = "Vanuatu", CountryCode = "VU" },
//new Country(){Name = "Viet Nam", CountryCode = "VN" },
//new Country(){Name = "Wallis and Futuna", CountryCode = "WF"},
//new Country(){Name = "Western Sahara", CountryCode = "EH" },
//new Country(){Name = "Yemen", CountryCode = "YE" },
//new Country(){Name = "Zambia", CountryCode = "ZM" },
//new Country(){Name = "Zimbabwe", CountryCode = "ZW" }
    };
    }
}
